# Setup
title: 七千气清
url: https://blog.co6co.top
paginate: 1
baseurl: ""
permalink: pretty
future: true


# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: co6co
  url: https://blog.co6co.top
  email: co6co@xx.com

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: 杂解
    url: /archive
  - title: q
    url: /aq

  - title: ME
    url: /about
