#scheme: Muse #默认 Scheme,这是 NexT 最初的版本，黑白主调，大量留白
scheme: Mist #紧凑版本，整洁有序的单栏外观
#scheme: Pisces #双栏 Scheme,小家碧玉似的清新
# Setup
title: 七千气清
url: https://blog.co6co.top
paginate: 10 # 每页显示的文章数
paginate_path: '/page:num/' # 分页链接格式
baseurl: ''
permalink: pretty
future: true
keywords: 技术,安全,工具,经验,博客
description: 一片数字星空，点缀着无数闪亮的思想火花，照亮前行的道路。

# Gems
#gems: [jekyll-coffeescript, jekyll-watch, jekyll-assets]
verbose: true # 创建加载顺序
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
#  - timezone_converter
#  - multi_posts

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
#ga_analytics: G-RKYV8PL5RB

# Specify the author for blog posts
author:
  name: co6co
  url: https://blog.co6co.top
  email: co6co@xx.com

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Blog
    url: /views/article
  - title: 分类
    url: /views/categories
  - title: 标签
    url: /views/tags
  - title: 安全相关
    url: /views/aq
  - title: 工具
    url: /pages/index
  - title: old
    url: /views/old
  - title: 测试
    url: /views/test
  - title: 关于
    url: /views/about

# 帖子
collections:
  new:
    output: true # Jekyll 会为集合中的每个文档生成一个单独的页面
    permalink: /tip/:path/
  article:
    output: true # Jekyll 会为集合中的每个文档生成一个单独的页面
    permalink: /article/:path/
  aq:
    output: true
    permalink: /aq/:path/
  old:
    output: true
    permalink: /old/:path/
  test:
    output: true
    permalink: /test/:path/
